version: '3'

env:
  IMG: algo
  NAME: kyoupuro

tasks:
  default:
    cmd: docker ps

  build:
    cmd: docker build . -t $IMG

  run:
    cmd: docker run --name $NAME -itd $IMG bash

  up:
    cmd: docker restart $NAME

  down:
    cmd: docker stop $NAME

  rm:
    cmd: docker rm $NAME

  prune:
    cmds:
      - docker stop $NAME
      - docker rm $NAME
      - docker rmi $IMG
