version: '3'

env:
  IMG: algo
  NAME: kyoupuro

tasks:
  default:
    cmd: docker ps

  build:
    cmd: docker build . -t $IMG

  run:
    cmd: docker run --name $NAME -itd $IMG bash

  up:
    cmds:
      - docker restart $NAME
      - echo "The $NAME container has been successfully started"

  down:
    cmds:
      - docker stop $NAME
      - echo "The $NAME container has stopped"
